language: objective-c
osx_image: xcode9.1
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace Example/Hokusai.xcworkspace -scheme Hokusai-Example -sdk iphonesimulator -destination 'OS=11.1,name=iPhone 6S Plus' ONLY_ACTIVE_ARCH=NO build

#before_install:
#  - brew update
#  - brew uninstall xctool && brew install --HEAD xctool
